create database personal
use PERSONAL


create table CLIENTES
(
ID_CLIENTE INT NOT NULL,
NOMBRE_C NVARCHAR (100) NOT NULL,
SEXO NCHAR (1) NOT NULL,
EDAD INT NOT NULL,
OBSERVACIONES NCHAR (100) NOT NULL
)

---CREACION DE PROCEDIMIENTOS ALMACENADOS
--INSERTAR CLIENTE

CREATE PROCEDURE SP_INSERTAR_CLIENTE
(
@ID_CLIENTE INT,
@NOMBRE_C NVARCHAR (100),
@SEXO NCHAR (1),
@EDAD INT,
@OBSERVACIONES NCHAR (100)
)
AS
BEGIN

INSERT CLIENTES (ID_CLIENTE,NOMBRE_C,SEXO,EDAD,OBSERVACIONES)
VALUES (@ID_CLIENTE,@NOMBRE_C,@SEXO,@EDAD,@OBSERVACIONES)
END

--MODIFICAR O ACTUALIZAR CLIENTE
CREATE PROCEDURE SP_MODIFICAR_CLIENTE
(
@ID_CLIENTE INT,
@NOMBRE_C NVARCHAR (100),
@SEXO NCHAR (1),
@EDAD INT,
@OBSERVACIONES NCHAR (100)
)
AS
BEGIN
UPDATE CLIENTES SET NOMBRE_C=@NOMBRE_C,SEXO=@SEXO,EDAD=@EDAD,OBSERVACIONES=@OBSERVACIONES
WHERE ID_CLIENTE=@ID_CLIENTE
END

--BUSCAR CLIENTE

CREATE PROCEDURE SP_BUSCAR_CLIENTE
(
@ID_CLIENTE INTEGER
)
AS
BEGIN
SELECT NOMBRE_C,SEXO,EDAD,OBSERVACIONES 
FROM CLIENTES
WHERE ID_CLIENTE = @ID_CLIENTE
END

--ELMINAR CLIENTE
CREATE PROCEDURE SP_ELIMINAR_CLIENTE
(
@ID_CLIENTE INT
)
AS
BEGIN
DELETE FROM CLIENTES
WHERE ID_CLIENTE=@ID_CLIENTE
END



